In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('loan_approval_dataset.csv')

In [3]:
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [4]:
data.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [5]:
data.columns=data.columns.str.strip()

In [6]:
for i in data.columns:
    if data[i].dtype=='object':
        data[i]=data[i].str.strip()
    else:
        continue

In [7]:
data['self_employed']=data['self_employed'].replace({'Yes':1,'No':0})

C:\Users\thaku\AppData\Local\Temp\ipykernel_27684\3335906444.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['self_employed']=data['self_employed'].replace({'Yes':1,'No':0})

In [8]:
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [9]:
x=data[['no_of_dependents','self_employed','income_annum','loan_amount','loan_term','cibil_score','residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value']]

In [10]:
x.head()

,no_of_dependents,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000

In [11]:
y=data['loan_status']

In [12]:
y.head()

0    Approved
1    Rejected
2    Rejected
3    Rejected
4    Rejected
Name: loan_status, dtype: object

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train.shape

(3415, 10)

In [16]:
x_test.shape

(854, 10)

In [17]:
y_train.shape

(3415,)

In [18]:
y_test.shape

(854,)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
clf2=DecisionTreeClassifier()
clf2.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
accuracy_score(y_test,clf2.predict(x_test))*100

97.7751756440281

In [23]:
accuracy_score(y_train,clf2.predict(x_train))*100

100.0

In [24]:
import joblib

In [25]:
joblib.dump(clf2,'loanaprv.joblib')

['loanaprv.joblib']